doggy/urls.py
from django.urls import path

from . import views

app_name = 'doggy'


urlpatterns = [
    path("", views.AnimalListView.as_view(), name="index"),
    path("<int:pk>/", views.AnimalDetailView.as_view(), name="detail"),
]

mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from mysite import settings

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("doggy/", include("doggy.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doggy/models.py
from django.db import models

# Create your models here.


class Breed(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(default=None)

    def __str__(self):
        return self.name


class Temper(models.Model):
    type_temper = models.CharField(max_length=30)

    def __str__(self):
        return self.type_temper


class Address(models.Model):
    name_shelter = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=30)
    street_building = models.CharField(max_length=30)
    contact_phone = models.CharField(max_length=12)
    work_hours = models.CharField(max_length=20)

    def __str__(self):
        return self.name_shelter


class Colour(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Medicament(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Vaccination(models.Model):
    name = models.ForeignKey(Medicament, on_delete=models.CASCADE, related_name='vaccination_name')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'


class Health(models.Model):
    class HealthState(models.IntegerChoices):
        UNKNOWN = 0
        HEALTHY = 1
        SICK = 2

    state = models.IntegerField(choices=HealthState, default=None)
    vaccination = models.ManyToManyField(Vaccination, related_name='vaccination_case')
    parasite_treatment = models.BooleanField()


class Animal(models.Model):
    objects = None

    class Gender(models.IntegerChoices):
        UNKNOWN = 0
        FEMALE = 1
        MALE = 2

    class Fur(models.IntegerChoices):
        UNKNOWN = 0
        LONG_HAIRED = 1
        MIDDLE_HAIRED = 2
        SHORT_HAIRED = 3

    name = models.CharField(max_length=30, blank=True)
    gender = models.IntegerField(choices=Gender, default=None)
    date_of_birth = models.DateField()
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, related_name='animal_breed')
    weight = models.PositiveIntegerField()
    height = models.PositiveIntegerField()
    temper = models.ForeignKey(Temper, on_delete=models.CASCADE, related_name='animal_temper')
    address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='animal_address')
    image = models.ImageField(blank=True, default="default.png")
    type_fur = models.IntegerField(choices=Fur, default=None)
    colour = models.ForeignKey(Colour, on_delete=models.CASCADE, related_name='animal_colour')
    life_story = models.TextField(max_length=500, blank=True)
    health_state = models.OneToOneField(Health, on_delete=models.CASCADE, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

doggy/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Animal

template_name = 'doggy/index.html'


def index(request: HttpRequest) -> HttpResponse:
    return render(
        request,
        template_name=template_name,
    )


class AnimalListView(ListView):
    # paginate_by = 2
    template_name = template_name
    queryset = Animal.objects.order_by("-pk").all()


class AnimalDetailView(DetailView):
    model = Animal

doggy/templates/doggy/animal_detail.html
{% extends 'base.html' %}
{% block title %} {{ object.name }} {% endblock %}
{% block content %}
    <ul>
        <li> {{ object.name }} </li>
        <li> {{ object.gender }} </li>
        <li> {{ object.breed }} </li>
        <li> {{ object.fur }} </li>
        <li> <img src="{{ object.image.url }}" width="40" height="60"> </li>
    </ul>
{% endblock %}

doggy/templates/doggy/filter.html
<h3> Filter Cities </h3>
{% for city in breeds %}
   {{ city.name }} Hello
{% endfor %}

doggy/templates/doggy/index.html
{% extends 'base.html' %}
{% block title %} Doggy {% endblock %}
{% block content %}

    {% include 'doggy/filter.html' %}
    {% load animal_tags %}

    {% current_time "%Y-%m-%d %I:%M %p" as the_time %}
    <p>The time is {{ the_time }}.</p>

    <h2>Content</h2>
    {% if page_obj %}
        {% include 'doggy/pagination.html' %}
    {% else %}
        {% for animal in object_list %}
            <li><a href="{% url 'doggy:detail' pk=animal.pk %}" > {{ animal.pk }} {{ animal.name|upper }} </a></li>
        {% endfor %}
    {% endif %}
{% endblock %}

doggy/templates/doggy/pagination.html
<ul>
{% for animal in page_obj %}
    <li><a href="{% url 'doggy:detail' pk=animal.pk %}" > {{ animal.pk }} {{ animal.name|upper }} </a></li>
{% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Сайт{% endblock %}</title>
    </head>
    <body>
        {% include 'components/navbar.html' %}
        {% block content %}
            <p>Скоро тут появится текст...</p>
        {% endblock %}
    </body>
</html>

templates/components/navbar.html
<nav>
  <ul>
    <li><a href="{% url 'index' %}">Main</a></li>
    <li><a href="{% url 'doggy:index' %}">Animals</a></li>
  </ul>
</nav>

templates/index.html
{% extends 'base.html' %}
{% block title %} Main {% endblock %}
{% block content %}
    Main Page
{% endblock %}